### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by proniotov** [pro-gamer007/simple-youtube-downloader#2]
# These are things I need to work on!
These are just things I have thought to work on for this. I've kept this as an issue so that I can come back to this and also so that people can give me ideas!

- [ ] Make this into a functional website
- [ ] Make an updating system [👀](https://www.electronjs.org/docs/tutorial/updates)
- [ ] Add a loading page [:eyes:](https://stackoverflow.com/questions/42292608/electron-loading-animation)
- [ ] Better way of updating the releases and making the release itself - rn needs a mac for mac releases...
- [x] Trays - needs to get put into the exe.
- [ ] Mobile version
- [ ] multi video format support
- [ ] playlists support

That's it for now... I'll update this when I'm done with something or when I add something new.

**Comment by Assassin-1234** [comment]
multi video format support

**Comment by proniotov** [comment]
very good idea, added!
Thanks!

**Comment by Assassin-1234** [comment]
playlists support

**Comment by proniotov** [comment]
added to the list
